### ISSUE TITLE
Chrome - fullscreen subtitles are not in right position.

### ISSUE THREAD

**Issue by xtsss** [SunnyLi/videojs-ass#1]
When going fullscreen on chrome, subtitles moves, are not visible or are in wrong position, on firefox everything works ok.
go here:
https://sunnyli.github.io/videojs-ass/example.html
on chrome and go fullscreen.

**Comment by SunnyLi** [comment]
Hmm.. I can't do anything about this unfortunately.
Since the problem was caused by changing the browser zoom level.

I couldn't find anyway to disable/reset the browser zoom level on desktop other than manually changing the CSS transform scale to make the font look like it was back at 100%, but the [browser zoom detection isn't reliable anymore](https://github.com/tombigel/detect-zoom).. so I don't think this can be fixed.

**Comment by xtsss** [comment]
Thanks, its ok, i justed didnt know previously that its caused by zoom, it can be as is, i will just go back to normal 100% page, without zooming, thanks :)

**Comment by Arnavion** [comment]
@SunnyLi 

Instead of trying to measure the browser zoom, why don't you try to resize to the player's width and height? Currently you resize to (screen.width, screen.height) in updateDisplayArea()

Eg: If I have a 1920x1200 monitor and the browser is zoomed to 200%, the fullscreen video element (iframe) is 960x600. However screen.width and screen.height continue to be 1920x1200 since they are measured in device pixels, not viewport pixels.

Instead of using screen.width and screen.height, it should use some method of getting the player's width and height. (It did not seem that player.width() and player.height() report it because they continued to give the pre-fullscreen dimensions. Not sure whether videojs can give that information.)

**Comment by SunnyLi** [comment]
@Arnavion 

You're right, but like you said there's currently no way to get the *updated* dimensions.
Also, videojs supports different source providers each having wrappers being implemented differently, so its not likely to have a unified method to access those video dimensions.
