### ISSUE TITLE
[Question] Possible to load a new subtitle file via JS?

### ISSUE THREAD

**Issue by ColorsCL** [SunnyLi/videojs-ass#17]
Hello, I just found this amazing plugin and I wanted to know if is possible to change/remove subtitles dynamically via JS?

I'm changing the video source via JS, but I also need to load a new subtitle file. Is this possible in any way?

Thanks in advance.

**Comment by SunnyLi** [comment]
No, that is not possible right now unfortunately..

I believe the only way to achieve something similar to what you
want is to create a new instance of the player with the plugin.

**Comment by ColorsCL** [comment]
The problem is that disposing the old player will remove the player from the html, and if that happens, it will close the fullscreen... Or at least I think so.

Thanks for the help 😄

**Comment by SunnyLi** [comment]
Yeah, that's what will happen.

The problem is that I'm not sure whether the underlying libjass implementation
can support swapping out subtitles. If I just manually unload and reload libjass
there'll definitely be memory leaks.. So a full refresh is the way to go since it
removes all existing references and therefore no leaks.

You're welcome 😃

**Comment by nupamore** [comment]
If you want to access libjass instance, export `renderer` of videojs-ass.
Then you can change ass instance
``` js 
libjass.ASS.fromUrl('subs/sample.ass')
.then( ass => {
  renderer._ass = ass
})
```
and add new dialogues.
``` js
renderer.ass.dialogues.push( new libjass.Dialogue(...) )
```

I'm developing editor with this solution.
http://dev.hassan.kr/flat
https://github.com/nupamore/Hsub-Editor

**Comment by SunnyLi** [comment]
Thanks, I think I've look into that method before but didn't go with it because I would have to manually add and delete each subtitle dialogue... which I was afraid that it could cause some oddities..
Anyways, I did come up with an alternative method which is to just have multiple instances of the `renderer` which should allow it to handle multiple subtitle tracks but I haven't got the time to commit it yet.. :/

**Comment by nupamore** [comment]
It's okay to slow down. I would be happy if I could export the `renderer`.

**Comment by SunnyLi** [comment]
@nupamore yeah, I looking to eventually update this plugin to use es6 and expose more of the internals.
Especially when after videojs 6 gets released.

**Comment by SunnyLi** [comment]
You should now be able to load new subtitle via JS.
See [here](https://github.com/SunnyLi/videojs-ass/commit/4548378156565f230f6f1c64fa7b20a65baa363d#diff-62ad28cc71ae9a54a611bc2d551533f6L36) for detail.
