### ISSUE TITLE
[Suggestion] Video Resize

### ISSUE THREAD

**Issue by Teranode** [SunnyLi/videojs-ass#18]
Consider putting

```
      window.addEventListener('resize', updateDisplayArea);
```

outside of player.fluid() that way it would update if someone is using window.resze();
to define their player width/height (normally this is done on the embedded server)

**Comment by SunnyLi** [comment]
Is there a scenario where you couldn't enable `player.fluid()` mode?
or does that not work properly on embedded server?

Would having another differently named event like `resize-player_id`
that triggers `updateDisplayArea` work for you? so that it only executes
on the player instance in question when there are multiple on the page.

**Comment by Teranode** [comment]
well, when i enabled fluid, the videos would get distorted, because the padding of the responsive fluid settings would shift the videos downward

**Comment by SunnyLi** [comment]
Sorry for the delay, after some thought I've made the exact change you've suggested
since it keeps everything simple and more likely to resolve your problem.
