### ISSUE TITLE
Jitter in the youtube example

### ISSUE THREAD

**Issue by Arnavion** [SunnyLi/videojs-ass#7]
The subs for the example video jitter a lot, especially for the lines using `\move`

The issue is the clock provided by `player.currentTime()` is very low-resolution - its value only updates every 250-500ms. However you set the [`autoPauseAfter` parameter of AutoClock](http://arnavion.github.io/libjass/api.xhtml#libjass.renderers.AutoClock) to [100ms.](https://github.com/SunnyLi/videojs-ass/blob/0696603/src/videojs.ass.js#L30) This means that when libjass's internal high-resolution clock and video.js's clock become more than 100ms apart, libjass will snap to video.js's clock (usually backwards) and then pause for the remaining time until the video.js clock updates again (snap forward). Because of this constant snapping and 150-400ms pauses the subs appear to jitter back and forth instead of moving smoothly.

This is from my testing with the youtube example, so I don't know if different video.js sources have different clock resolutions. Atleast for that one, you get a better experience with `clock = new libjass.renderers.AutoClock(getCurrentTime, 500);` and reducing the delay from -0.45 to -0.1

**Comment by SunnyLi** [comment]
Ok, thanks for the suggestion I will update it.

The demo actually haven't been updated for quite some time (if that's what you used since you mentioned YouTube example) and is still using videojs `v4` while the latest version runs on `v5`. I'm confused as to how you get the YouTube example with `AutoClock` as the [demo source](https://github.com/SunnyLi/videojs-ass/blob/c3a454d717c0cde36145a9ce7315ed078ccaeaf6/src/videojs.ass.js) doesn't have it yet??

**Comment by Arnavion** [comment]
I downloaded your example site, replaced example.html and videojs.ass.js with the ones from v5 branch and added back the youtube code from master branch, updated videojs-youtube to the latest version that uses video.js v5, and updated example.html to work with the new API (src string -> sources array)

**Comment by SunnyLi** [comment]
Awesome, I've updated it now. :smile:
